name: Docker Image CI

on:
  push:
    branches: [ "build/rmf" ]
  pull_request:
    branches: [ "build/rmf" ]

jobs:
  build:
    runs-on: ubuntu-latest
    ##############################################################
    ## Configurations
    ##############################################################
    env:
      builder_ns: ghcr.io/open-rmf/rmf_deployment_template
      registry: docker.io
      domain_url: rmf-deployment-template.open-rmf.org
    ##############################################################
    steps:
      # ###
      # Login to github packages, our container registry
      # ###
      # - name: Login to Github Packages
      #  uses: docker/login-action@v1
      #  with:
      #    registry: ghcr.io
      #    username: ${{ github.actor }}
      #    password: ${{ secrets.GHCR_PAT }}
      -
        name: Checkout
        uses: actions/checkout@v3
      - 
        name: Run vcs import rmf
        run: |
          mkdir src
          vcs import src < rmf/rmf.repos  || true
      # ###
      # build builder images
      # ###
      -
        name: Build builder-rosdep
        uses: docker/build-push-action@v3
        with:
          context: .
          file: rmf/builder-rosdep.Dockerfile
          build-args: |
            REGISTRY=${{ env.registry }}
          # push: true
          tags: ${{ env.builder_ns }}/builder-rosdep:latest
      -
        name: Build builder-rmf
        uses: docker/build-push-action@v3
        with:
          context: .
          file: rmf/builder-rmf.Dockerfile
          build-args: |
            BUILDER_NS=${{ env.builder_ns }}
          # push: true
          tags: ${{ env.builder_ns }}/builder-rmf:latest
      - 
        name: run vcs import rmf-web
        run: |
          mkdir rmf-web-src
          vcs import rmf-web-src < rmf-web/rmf-web.repos
      -
        name: Build builder-rmf-web
        uses: docker/build-push-action@v3
        with:
          context: .
          file: rmf-web/builder-rmf-web.Dockerfile
          build-args: |
            BUILDER_NS=${{ env.builder_ns }}
          # push: true
          tags: ${{ env.builder_ns }}/builder-rmf-web:latest
      - 
        name: run vcs import rmf-simulation
        run: |
          mkdir rmf-simulation-src
          vcs import rmf-simulation-src < rmf-simulation/rmf-simulation.repos
      -
        name: Build builder-rmf-simulation
        uses: docker/build-push-action@v3
        with:
          context: .
          file: rmf-simulation/builder-rmf-simulation.Dockerfile
          build-args: |
            BUILDER_NS=${{ env.builder_ns }}
          # push: true
          tags: ${{ env.builder_ns }}/builder-rmf-simulation:latest
      # ###
      # build rmf image
      # ###
      -
        name: Build rmf docker img
        uses: docker/build-push-action@v3
        with:
          context: .
          file: rmf/rmf.Dockerfile
          build-args: |
            BUILDER_NS=${{ env.builder_ns }}
          # push: true
          tags: ${{ env.builder_ns }}/rmf:latest
      # ###
      # build rmf simulation images
      # ###
      -
        name: Build rmf-simulation
        uses: docker/build-push-action@v3
        with:
          context: .
          file: rmf-simulation/rmf-simulation.Dockerfile
          build-args: |
            BUILDER_NS=${{ env.builder_ns }}
          # push: true
          tags: ${{ env.builder_ns }}/rmf-simulation:latest
      # ###
      # build rmf web images
      # ###
      -
        name: Build rmf-web-rmf-server
        uses: docker/build-push-action@v3
        with:
          context: .
          file: rmf-web/rmf-web-rmf-server.Dockerfile
          build-args: |
            BUILDER_NS=${{ env.builder_ns }}
          # push: true
          tags: ${{ env.builder_ns }}/rmf-web-rmf-server:latest
      -
        name: Build rmf-web-dashboard
        uses: docker/build-push-action@v3
        with:
          context: .
          file: rmf-web/rmf-web-dashboard.Dockerfile
          build-args: |
            REGISTRY=${{ env.registry }}
            DOMAIN_URL=${{ env.domain_url }}
            BUILDER_NS=${{ env.builder_ns }}
          # push: true
          tags: ${{ env.builder_ns }}/rmf-web-dashboard:latest
