name: Lint all charts

on: 
  pull_request:
#    paths:
#      - charts/**
  push:
    branches: [wip-deploy]
#    paths:
#      - charts/**
jobs:
  lint-test:
    runs-on: ubuntu-latest
    env:
      chart_configuration: --charts charts/
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Helm
        uses: azure/setup-helm@v3
        with:
          version: v3.11.2

      - uses: actions/setup-python@v4
        with:
          python-version: '3.11'
          check-latest: true

      - name: Set up chart-testing
        uses: helm/chart-testing-action@v2.6.1

      - name: Run chart-testing (lint)
        run: ct lint ${chart_configuration}
